### ISSUE TITLE
[EPIC]: QAI (Attenuation Imaging) Cut-off Values Introduction

### ISSUE THREAD

**Issue by antpass79** [ESAOTE-SW-ULS/overall-priority-list-simulation#8]
### Epic description

Introduction managing cut-off values for QAI measurements (dB / cm / MHz) performed on liver.
The cut off will be suggested to the primary end user according to the data available in literature from the scientific society operating in the specific field of practice
Cut-offs shall be available within the device.
QAI measure and related cut-off shall be displayed on Mainscreen and then available in the Report under the user supervision
The cut-offs will be inserted for Abdominal application for Convex applicable probes

### Associated stories

- [ ] Add Attenuation index and cut-off values in QAI menu
- [ ] QAI 2DQElaxto: exit from the tool the measure shall not be deleted
- [ ] QAI:  the possibility to customize the acquisiton ROI dimension
- [ ] Attenuation Imaging - Tuning on CX1-8 - Mylab9
- [ ] Attenuation Imaging - Tuning on CX1-8 - MylabX90
- [ ] QAI:add possibility to show cut-offs on palette after acquisition and measured values after roi's positioning
